services:
  - type: web
    name: fitly
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    autoDeployTrigger: checksPass
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: supabase
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_DB_USERNAME
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: JPA_DDL_AUTO
        value: update
      - key: DB_MAX_POOL_SIZE
        value: "5"
      - key: DB_MIN_IDLE
        value: "1"

