begin;

-- FITLY ERD3 physical schema.
-- The logical USER entity is implemented as app_user because USER is a
-- PostgreSQL keyword. All timestamps are stored as timestamptz/UTC.

create schema if not exists private;
revoke all on schema private from public;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke execute on function private.set_updated_at() from public, anon, authenticated, service_role;

-- 01 USER / AUTH

create table public.app_user (
  user_id bigint generated by default as identity,
  email varchar(255) not null,
  password_hash varchar(255) not null,
  name varchar(100) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_user_pkey primary key (user_id),
  constraint app_user_email_key unique (email),
  constraint app_user_email_not_blank_check check (btrim(email) <> ''),
  constraint app_user_name_not_blank_check check (btrim(name) <> '')
);

create table public.role (
  role_id bigint generated by default as identity,
  role_name varchar(30) not null,
  constraint role_pkey primary key (role_id),
  constraint role_role_name_key unique (role_name),
  constraint role_role_name_check check (role_name in ('CUSTOMER', 'ENTERPRISE', 'ADMIN'))
);

create table public.user_role (
  user_id bigint not null,
  role_id bigint not null,
  constraint user_role_pkey primary key (user_id, role_id),
  constraint user_role_user_id_fkey foreign key (user_id)
    references public.app_user (user_id) on delete cascade,
  constraint user_role_role_id_fkey foreign key (role_id)
    references public.role (role_id) on delete restrict
);

create table public.user_profile (
  user_id bigint not null,
  default_size varchar(30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_profile_pkey primary key (user_id),
  constraint user_profile_user_id_fkey foreign key (user_id)
    references public.app_user (user_id) on delete cascade
);

create table public.style (
  style_id bigint generated by default as identity,
  style_name varchar(50) not null,
  constraint style_pkey primary key (style_id),
  constraint style_style_name_key unique (style_name),
  constraint style_style_name_check check (style_name in ('Minimal', 'Formal', 'Street', 'Casual'))
);

create table public.user_preferred_style (
  user_id bigint not null,
  style_id bigint not null,
  created_at timestamptz not null default now(),
  constraint user_preferred_style_pkey primary key (user_id, style_id),
  constraint user_preferred_style_user_id_fkey foreign key (user_id)
    references public.app_user (user_id) on delete cascade,
  constraint user_preferred_style_style_id_fkey foreign key (style_id)
    references public.style (style_id) on delete restrict
);

-- 02 BUSINESS / PRODUCT / ENTERPRISE AI

create table public.business (
  business_id bigint generated by default as identity,
  business_name varchar(200) not null,
  business_number varchar(50) not null,
  business_type varchar(20) not null,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_pkey primary key (business_id),
  constraint business_business_number_key unique (business_number),
  constraint business_name_not_blank_check check (btrim(business_name) <> ''),
  constraint business_business_type_check check (business_type in ('PLATFORM', 'SHOP', 'BRAND')),
  constraint business_status_check check (status in ('ACTIVE', 'INACTIVE'))
);

create table public.business_member (
  business_member_id bigint generated by default as identity,
  business_id bigint not null,
  user_id bigint not null,
  member_role varchar(20) not null,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  constraint business_member_pkey primary key (business_member_id),
  constraint business_member_business_user_key unique (business_id, user_id),
  constraint business_member_business_id_fkey foreign key (business_id)
    references public.business (business_id) on delete restrict,
  constraint business_member_user_id_fkey foreign key (user_id)
    references public.app_user (user_id) on delete restrict,
  constraint business_member_member_role_check check (member_role in ('OWNER', 'MANAGER', 'MD', 'STAFF')),
  constraint business_member_status_check check (status in ('ACTIVE', 'INACTIVE'))
);

create table public.business_contract (
  contract_id bigint generated by default as identity,
  business_id bigint not null,
  commission_rate numeric(5,4) not null,
  start_date date not null,
  end_date date,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  constraint business_contract_pkey primary key (contract_id),
  constraint business_contract_business_id_fkey foreign key (business_id)
    references public.business (business_id) on delete restrict,
  constraint business_contract_commission_rate_check check (commission_rate between 0 and 1),
  constraint business_contract_date_range_check check (end_date is null or start_date <= end_date),
  constraint business_contract_status_check check (status in ('ACTIVE', 'EXPIRED', 'TERMINATED'))
);

create table public.product (
  product_id bigint generated by default as identity,
  business_id bigint not null,
  created_by_business_member_id bigint not null,
  product_name varchar(200) not null,
  brand_name varchar(100) not null,
  category varchar(30) not null,
  original_price bigint not null,
  rental_price bigint not null,
  description text not null,
  image_url text not null,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_pkey primary key (product_id),
  constraint product_business_id_fkey foreign key (business_id)
    references public.business (business_id) on delete restrict,
  constraint product_created_by_business_member_id_fkey foreign key (created_by_business_member_id)
    references public.business_member (business_member_id) on delete restrict,
  constraint product_name_not_blank_check check (btrim(product_name) <> ''),
  constraint product_category_check check (category in ('TOP', 'BOTTOM', 'OUTER', 'SHOES', 'ACCESSORY')),
  constraint product_original_price_check check (original_price >= 0),
  constraint product_rental_price_check check (rental_price >= 0),
  constraint product_status_check check (status in ('DRAFT', 'ACTIVE', 'INACTIVE'))
);

create table public.product_description_generation (
  generation_id bigint generated by default as identity,
  business_id bigint not null,
  created_by_business_member_id bigint not null,
  product_id bigint,
  input_image_url text not null,
  generated_description text,
  generation_status varchar(20) not null,
  created_at timestamptz not null default now(),
  constraint product_description_generation_pkey primary key (generation_id),
  constraint product_description_generation_business_id_fkey foreign key (business_id)
    references public.business (business_id) on delete restrict,
  constraint product_description_generation_member_id_fkey foreign key (created_by_business_member_id)
    references public.business_member (business_member_id) on delete restrict,
  constraint product_description_generation_product_id_fkey foreign key (product_id)
    references public.product (product_id) on delete set null,
  constraint product_description_generation_status_check
    check (generation_status in ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

create table public.product_variant (
  variant_id bigint generated by default as identity,
  product_id bigint not null,
  size varchar(30) not null,
  sku varchar(100),
  total_stock integer not null,
  available_stock integer not null,
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_variant_pkey primary key (variant_id),
  constraint product_variant_product_size_key unique (product_id, size),
  constraint product_variant_product_id_fkey foreign key (product_id)
    references public.product (product_id) on delete restrict,
  constraint product_variant_stock_check
    check (total_stock >= 0 and available_stock >= 0 and available_stock <= total_stock),
  constraint product_variant_status_check check (status in ('ACTIVE', 'OUT_OF_STOCK', 'INACTIVE'))
);

-- 03 CUSTOMER / AI RECOMMENDATION

create table public.wardrobe_item (
  wardrobe_item_id bigint generated by default as identity,
  user_id bigint not null,
  image_url text not null,
  item_name varchar(200) not null,
  category varchar(30) not null,
  color varchar(50) not null,
  ai_detected_category varchar(30),
  ai_detected_color varchar(50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wardrobe_item_pkey primary key (wardrobe_item_id),
  constraint wardrobe_item_user_id_fkey foreign key (user_id)
    references public.app_user (user_id) on delete cascade,
  constraint wardrobe_item_name_not_blank_check check (btrim(item_name) <> ''),
  constraint wardrobe_item_category_check check (category in ('TOP', 'BOTTOM', 'OUTER', 'SHOES', 'ACCESSORY')),
  constraint wardrobe_item_ai_category_check check (
    ai_detected_category is null
    or ai_detected_category in ('TOP', 'BOTTOM', 'OUTER', 'SHOES', 'ACCESSORY')
  )
);

create table public.recommendation_request (
  request_id bigint generated by default as identity,
  user_id bigint not null,
  style_id bigint not null,
  tpo varchar(50) not null,
  size varchar(30),
  status varchar(20) not null,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint recommendation_request_pkey primary key (request_id),
  constraint recommendation_request_user_id_fkey foreign key (user_id)
    references public.app_user (user_id) on delete restrict,
  constraint recommendation_request_style_id_fkey foreign key (style_id)
    references public.style (style_id) on delete restrict,
  constraint recommendation_request_tpo_not_blank_check check (btrim(tpo) <> ''),
  constraint recommendation_request_status_check check (status in ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  constraint recommendation_request_completed_at_check check (status <> 'COMPLETED' or completed_at is not null)
);

create table public.recommendation_request_wardrobe (
  request_id bigint not null,
  wardrobe_item_id bigint not null,
  constraint recommendation_request_wardrobe_pkey primary key (request_id, wardrobe_item_id),
  constraint recommendation_request_wardrobe_request_id_fkey foreign key (request_id)
    references public.recommendation_request (request_id) on delete cascade,
  constraint recommendation_request_wardrobe_item_id_fkey foreign key (wardrobe_item_id)
    references public.wardrobe_item (wardrobe_item_id) on delete restrict
);

create table public.recommendation (
  recommendation_id bigint generated by default as identity,
  request_id bigint not null,
  rank integer not null,
  matching_score numeric(5,4) not null,
  styling_comment text not null,
  created_at timestamptz not null default now(),
  constraint recommendation_pkey primary key (recommendation_id),
  constraint recommendation_request_rank_key unique (request_id, rank),
  constraint recommendation_request_id_fkey foreign key (request_id)
    references public.recommendation_request (request_id) on delete cascade,
  constraint recommendation_rank_check check (rank > 0),
  constraint recommendation_matching_score_check check (matching_score between 0 and 1)
);

create table public.outfit_feedback (
  feedback_id bigint generated by default as identity,
  recommendation_id bigint not null,
  sentiment varchar(20) not null,
  reason_code varchar(50),
  feedback_text text,
  created_at timestamptz not null default now(),
  constraint outfit_feedback_pkey primary key (feedback_id),
  constraint outfit_feedback_recommendation_id_key unique (recommendation_id),
  constraint outfit_feedback_recommendation_id_fkey foreign key (recommendation_id)
    references public.recommendation (recommendation_id) on delete cascade,
  constraint outfit_feedback_sentiment_check check (sentiment in ('LIKE', 'DISLIKE'))
);

create table public.recommendation_item (
  recommendation_item_id bigint generated by default as identity,
  recommendation_id bigint not null,
  wardrobe_item_id bigint,
  product_variant_id bigint,
  source_type varchar(20) not null,
  price_snapshot bigint,
  sort_order integer not null,
  constraint recommendation_item_pkey primary key (recommendation_item_id),
  constraint recommendation_item_recommendation_sort_key unique (recommendation_id, sort_order),
  constraint recommendation_item_recommendation_id_fkey foreign key (recommendation_id)
    references public.recommendation (recommendation_id) on delete cascade,
  constraint recommendation_item_wardrobe_item_id_fkey foreign key (wardrobe_item_id)
    references public.wardrobe_item (wardrobe_item_id) on delete restrict,
  constraint recommendation_item_product_variant_id_fkey foreign key (product_variant_id)
    references public.product_variant (variant_id) on delete restrict,
  constraint recommendation_item_source_type_check check (source_type in ('WARDROBE', 'RENTAL_PRODUCT')),
  constraint recommendation_item_price_snapshot_check check (price_snapshot is null or price_snapshot >= 0),
  constraint recommendation_item_sort_order_check check (sort_order > 0),
  constraint recommendation_item_source_consistency_check check (
    (
      source_type = 'WARDROBE'
      and wardrobe_item_id is not null
      and product_variant_id is null
      and price_snapshot is null
    )
    or
    (
      source_type = 'RENTAL_PRODUCT'
      and wardrobe_item_id is null
      and product_variant_id is not null
      and price_snapshot is not null
    )
  )
);

-- 04 RENTAL / RETURN

create table public.rental_order (
  rental_order_id bigint generated by default as identity,
  user_id bigint not null,
  source_recommendation_id bigint,
  order_type varchar(20) not null,
  status varchar(20) not null,
  payment_status varchar(20) not null,
  rental_start_date date not null,
  rental_end_date date not null,
  delivery_address text not null,
  total_amount bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rental_order_pkey primary key (rental_order_id),
  constraint rental_order_user_id_fkey foreign key (user_id)
    references public.app_user (user_id) on delete restrict,
  constraint rental_order_source_recommendation_id_fkey foreign key (source_recommendation_id)
    references public.recommendation (recommendation_id) on delete set null,
  constraint rental_order_order_type_check check (order_type in ('PERSONAL', 'GROUP')),
  constraint rental_order_status_check
    check (status in ('ORDERED', 'PREPARING', 'SHIPPED', 'RENTING', 'RETURN_DUE', 'COMPLETED', 'CANCELLED')),
  constraint rental_order_payment_status_check check (payment_status in ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
  constraint rental_order_date_range_check check (rental_start_date <= rental_end_date),
  constraint rental_order_delivery_address_not_blank_check check (btrim(delivery_address) <> ''),
  constraint rental_order_total_amount_check check (total_amount >= 0)
);

create table public.rental_item (
  rental_item_id bigint generated by default as identity,
  rental_order_id bigint not null,
  product_variant_id bigint not null,
  rental_price_snapshot bigint not null,
  status varchar(20) not null,
  converted_to_own_at timestamptz,
  additional_purchase_amount bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rental_item_pkey primary key (rental_item_id),
  constraint rental_item_rental_order_id_fkey foreign key (rental_order_id)
    references public.rental_order (rental_order_id) on delete restrict,
  constraint rental_item_product_variant_id_fkey foreign key (product_variant_id)
    references public.product_variant (variant_id) on delete restrict,
  constraint rental_item_rental_price_snapshot_check check (rental_price_snapshot >= 0),
  constraint rental_item_status_check check (status in ('RENTED', 'RETURN_REQUESTED', 'RETURNED', 'PURCHASED')),
  constraint rental_item_additional_purchase_amount_check
    check (additional_purchase_amount is null or additional_purchase_amount >= 0),
  constraint rental_item_purchase_consistency_check check (
    (
      status = 'PURCHASED'
      and converted_to_own_at is not null
      and additional_purchase_amount is not null
    )
    or
    (
      status <> 'PURCHASED'
      and converted_to_own_at is null
      and additional_purchase_amount is null
    )
  )
);

create table public.group_rental_detail (
  rental_order_id bigint not null,
  purpose varchar(100) not null,
  participant_count integer not null,
  created_at timestamptz not null default now(),
  constraint group_rental_detail_pkey primary key (rental_order_id),
  constraint group_rental_detail_rental_order_id_fkey foreign key (rental_order_id)
    references public.rental_order (rental_order_id) on delete cascade,
  constraint group_rental_detail_purpose_not_blank_check check (btrim(purpose) <> ''),
  constraint group_rental_detail_participant_count_check check (participant_count > 0)
);

create table public.group_rental_request_item (
  group_request_item_id bigint generated by default as identity,
  rental_order_id bigint not null,
  category varchar(30) not null,
  requested_quantity integer not null,
  constraint group_rental_request_item_pkey primary key (group_request_item_id),
  constraint group_rental_request_item_rental_order_id_fkey foreign key (rental_order_id)
    references public.rental_order (rental_order_id) on delete cascade,
  constraint group_rental_request_item_category_check
    check (category in ('TOP', 'BOTTOM', 'OUTER', 'SHOES', 'ACCESSORY')),
  constraint group_rental_request_item_requested_quantity_check check (requested_quantity > 0)
);

create table public.return_process (
  return_process_id bigint generated by default as identity,
  rental_item_id bigint not null,
  processed_by_admin_user_id bigint,
  return_status varchar(20) not null,
  inspection_status varchar(20) not null,
  inspection_grade varchar(20),
  laundry_status varchar(20) not null,
  inventory_restored boolean not null default false,
  return_requested_at timestamptz not null,
  returned_at timestamptz,
  inspected_at timestamptz,
  cleaned_at timestamptz,
  inventory_restored_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint return_process_pkey primary key (return_process_id),
  constraint return_process_rental_item_id_key unique (rental_item_id),
  constraint return_process_rental_item_id_fkey foreign key (rental_item_id)
    references public.rental_item (rental_item_id) on delete restrict,
  constraint return_process_admin_user_id_fkey foreign key (processed_by_admin_user_id)
    references public.app_user (user_id) on delete restrict,
  constraint return_process_return_status_check check (return_status in ('REQUESTED', 'RETURNED', 'COMPLETED')),
  constraint return_process_inspection_status_check check (inspection_status in ('PENDING', 'INSPECTING', 'COMPLETED')),
  constraint return_process_inspection_grade_check
    check (inspection_grade is null or inspection_grade in ('NORMAL', 'MINOR_STAIN', 'DAMAGED')),
  constraint return_process_laundry_status_check check (laundry_status in ('PENDING', 'CLEANING', 'COMPLETED')),
  constraint return_process_inventory_restored_at_check
    check (not inventory_restored or inventory_restored_at is not null)
);

-- 05 SETTLEMENT

create table public.business_settlement (
  settlement_id bigint generated by default as identity,
  contract_id bigint not null,
  period_start date not null,
  period_end date not null,
  rental_gross_amount bigint not null,
  rent_to_own_gross_amount bigint not null,
  commission_amount bigint not null,
  settlement_amount bigint not null,
  status varchar(20) not null,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  constraint business_settlement_pkey primary key (settlement_id),
  constraint business_settlement_contract_period_key unique (contract_id, period_start, period_end),
  constraint business_settlement_contract_id_fkey foreign key (contract_id)
    references public.business_contract (contract_id) on delete restrict,
  constraint business_settlement_period_check check (period_start <= period_end),
  constraint business_settlement_rental_gross_amount_check check (rental_gross_amount >= 0),
  constraint business_settlement_rent_to_own_gross_amount_check check (rent_to_own_gross_amount >= 0),
  constraint business_settlement_commission_amount_check check (commission_amount >= 0),
  constraint business_settlement_settlement_amount_check check (settlement_amount >= 0),
  constraint business_settlement_status_check check (status in ('PENDING', 'SETTLED', 'FAILED')),
  constraint business_settlement_settled_at_check check (status <> 'SETTLED' or settled_at is not null)
);

-- Frequently queried foreign keys and workflow filters.

create index user_role_role_id_idx on public.user_role (role_id);
create index user_preferred_style_style_id_idx on public.user_preferred_style (style_id);
create index business_member_user_id_idx on public.business_member (user_id);
create index business_contract_business_id_idx on public.business_contract (business_id);
create unique index business_contract_one_active_per_business_idx
  on public.business_contract (business_id) where status = 'ACTIVE';
create index product_business_id_idx on public.product (business_id);
create index product_created_by_member_id_idx on public.product (created_by_business_member_id);
create index product_active_category_idx on public.product (category, created_at desc) where status = 'ACTIVE';
create index product_description_generation_business_id_idx
  on public.product_description_generation (business_id);
create index product_description_generation_member_id_idx
  on public.product_description_generation (created_by_business_member_id);
create index product_description_generation_product_id_idx
  on public.product_description_generation (product_id) where product_id is not null;
create unique index product_variant_sku_key
  on public.product_variant (sku) where sku is not null;
create index wardrobe_item_user_created_at_idx on public.wardrobe_item (user_id, created_at desc);
create index recommendation_request_user_created_at_idx
  on public.recommendation_request (user_id, created_at desc);
create index recommendation_request_style_id_idx on public.recommendation_request (style_id);
create index recommendation_request_wardrobe_item_id_idx
  on public.recommendation_request_wardrobe (wardrobe_item_id);
create index recommendation_item_wardrobe_item_id_idx
  on public.recommendation_item (wardrobe_item_id) where wardrobe_item_id is not null;
create index recommendation_item_product_variant_id_idx
  on public.recommendation_item (product_variant_id) where product_variant_id is not null;
create index rental_order_user_created_at_idx on public.rental_order (user_id, created_at desc);
create index rental_order_source_recommendation_id_idx
  on public.rental_order (source_recommendation_id) where source_recommendation_id is not null;
create index rental_order_active_return_due_idx
  on public.rental_order (rental_end_date, status)
  where status in ('SHIPPED', 'RENTING', 'RETURN_DUE');
create index rental_item_rental_order_id_idx on public.rental_item (rental_order_id);
create index rental_item_product_variant_id_idx on public.rental_item (product_variant_id);
create index group_rental_request_item_rental_order_id_idx
  on public.group_rental_request_item (rental_order_id);
create index return_process_admin_user_id_idx
  on public.return_process (processed_by_admin_user_id) where processed_by_admin_user_id is not null;
create index return_process_workflow_idx
  on public.return_process (return_status, inspection_status, laundry_status)
  where not inventory_restored;
create index business_settlement_pending_idx
  on public.business_settlement (created_at) where status = 'PENDING';

-- Keep updated_at consistent without relying on every application code path.

create trigger app_user_set_updated_at
before update on public.app_user
for each row execute function private.set_updated_at();

create trigger user_profile_set_updated_at
before update on public.user_profile
for each row execute function private.set_updated_at();

create trigger business_set_updated_at
before update on public.business
for each row execute function private.set_updated_at();

create trigger product_set_updated_at
before update on public.product
for each row execute function private.set_updated_at();

create trigger product_variant_set_updated_at
before update on public.product_variant
for each row execute function private.set_updated_at();

create trigger wardrobe_item_set_updated_at
before update on public.wardrobe_item
for each row execute function private.set_updated_at();

create trigger rental_order_set_updated_at
before update on public.rental_order
for each row execute function private.set_updated_at();

create trigger rental_item_set_updated_at
before update on public.rental_item
for each row execute function private.set_updated_at();

create trigger return_process_set_updated_at
before update on public.return_process
for each row execute function private.set_updated_at();

-- The Spring Boot application uses a direct PostgreSQL connection. Keep the
-- Data API closed until an explicit Supabase Auth/RLS access model is added.

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'app_user', 'role', 'user_role', 'user_profile', 'style', 'user_preferred_style',
    'business', 'business_member', 'business_contract', 'product',
    'product_description_generation', 'product_variant', 'wardrobe_item',
    'recommendation_request', 'recommendation_request_wardrobe', 'recommendation',
    'outfit_feedback', 'recommendation_item', 'rental_order', 'rental_item',
    'group_rental_detail', 'group_rental_request_item', 'return_process',
    'business_settlement'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format(
      'revoke all on table public.%I from anon, authenticated, service_role',
      table_name
    );
  end loop;
end;
$$;

revoke all on all sequences in schema public from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke all on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated, service_role;

insert into public.role (role_name)
values ('CUSTOMER'), ('ENTERPRISE'), ('ADMIN');

insert into public.style (style_name)
values ('Minimal'), ('Formal'), ('Street'), ('Casual');

commit;
