begin;

create table if not exists public.recommendation_feedback (
  feedback_id bigint generated by default as identity,
  recommendation_job_id bigint not null,
  customer_id bigint not null,
  sentiment varchar(20) not null,
  reason_code varchar(50),
  feedback_text varchar(1000),
  updated_at timestamptz not null default now(),
  constraint recommendation_feedback_pkey primary key (feedback_id),
  constraint recommendation_feedback_job_key unique (recommendation_job_id),
  constraint recommendation_feedback_job_fkey foreign key (recommendation_job_id)
    references public.recommendation_request (request_id) on delete cascade,
  constraint recommendation_feedback_customer_fkey foreign key (customer_id)
    references public.app_user (user_id) on delete restrict,
  constraint recommendation_feedback_sentiment_check check (sentiment in ('LIKE', 'DISLIKE'))
);

create index if not exists recommendation_feedback_customer_idx
  on public.recommendation_feedback (customer_id, updated_at desc);

alter table public.recommendation_feedback enable row level security;
revoke all on table public.recommendation_feedback from anon, authenticated, service_role;
revoke all on sequence public.recommendation_feedback_feedback_id_seq from anon, authenticated, service_role;

commit;
